export const actionType = {
  // auth
  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  // project
  FETCH_ALL_PROJECTS_REQUEST: "FETCH_ALL_PROJECTS_REQUEST",
  FETCH_ALL_PROJECTS_SUCCESS: "FETCH_ALL_PROJECTS_SUCCESS",
  FETCH_ALL_PROJECTS_FAILURE: "FETCH_ALL_PROJECTS_FAILURE",

  FETCH_PROJECT_CATEGORIES_REQUEST: "FETCH_PROJECT_CATEGORIES_REQUEST",
  FETCH_PROJECT_CATEGORIES_SUCCESS: "FETCH_PROJECT_CATEGORIES_SUCCESS",
  FETCH_PROJECT_CATEGORIES_FAILURE: "FETCH_PROJECT_CATEGORIES_FAILURE",

  FETCH_PROJECT_DETAILS_REQUEST: "FETCH_PROJECT_DETAILS_REQUEST",
  FETCH_PROJECT_DETAILS_SUCCESS: "FETCH_PROJECT_DETAILS_SUCCESS",
  FETCH_PROJECT_DETAILS_FAILURE: "FETCH_PROJECT_DETAILS_FAILURE",

  CREATE_PROJECT_REQUEST: "CREATE_PROJECT_REQUEST",
  CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",
  CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",

  UPDATE_PROJECT_REQUEST: "UPDATE_PROJECT_REQUEST",
  UPDATE_PROJECT_SUCCESS: "UPDATE_PROJECT_SUCCESS",
  UPDATE_PROJECT_FAILURE: "UPDATE_PROJECT_FAILURE",

  // task
  FETCH_TASK_TYPES_REQUEST: "FETCH_TASK_TYPES_REQUEST",
  FETCH_TASK_TYPES_SUCCESS: "FETCH_TASK_TYPES_SUCCESS",
  FETCH_TASK_TYPES_FAILURE: "FETCH_TASK_TYPES_FAILURE",

  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",

  UPDATE_TASK_STATUS_REQUEST: "UPDATE_TASK_STATUS_REQUEST",
  UPDATE_TASK_STATUS_SUCCESS: "UPDATE_TASK_STATUS_SUCCESS",
  UPDATE_TASK_STATUS_FAILURE: "UPDATE_TASK_STATUS_FAILURE",
};
