export const actionType = {
  SIGN_IN_REQUEST: "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  FETCH_ALL_PROJECTS_REQUEST: "FETCH_ALL_PROJECTS_REQUEST",
  FETCH_ALL_PROJECTS_SUCCESS: "FETCH_ALL_PROJECTS_SUCCESS",
  FETCH_ALL_PROJECTS_FAILURE: "FETCH_ALL_PROJECTS_FAILURE",

  FETCH_PROJECT_CATEGORIES_REQUEST: "FETCH_PROJECT_CATEGORIES_REQUEST",
  FETCH_PROJECT_CATEGORIES_SUCCESS: "FETCH_PROJECT_CATEGORIES_SUCCESS",
  FETCH_PROJECT_CATEGORIES_FAILURE: "FETCH_PROJECT_CATEGORIES_FAILURE",

  CREATE_PROJECT_REQUEST: "CREATE_PROJECT_REQUEST",
  CREATE_PROJECT_SUCCESS: "CREATE_PROJECT_SUCCESS",
  CREATE_PROJECT_FAILURE: "CREATE_PROJECT_FAILURE",
};
